hpcc-systems/hpcc-jdbc

docs/JDBCDriver/hpcc_jdbc_driver.xml
docs/common/Version.xml

FIX JDBC-3 explicit URL Prefix 
Signed-off-by: G Panagiotatos <g.pan3.14@gmail.com>

JDBC-3 explicit URL Prefix

---

pom.xml

INTERNAL beta-0.3.0 branch

---

src/main/java/org/hpccsystems/jdbcdriver/HPCCConnection.java
src/main/java/org/hpccsystems/jdbcdriver/HPCCDatabaseMetaData.java
src/main/java/org/hpccsystems/jdbcdriver/HPCCDriver.java
src/main/java/org/hpccsystems/jdbcdriver/HPCCJDBCUtils.java
src/main/java/org/hpccsystems/jdbcdriver/HPCCResultSet.java
src/main/java/org/hpccsystems/jdbcdriver/HPCCStatement.java

Cleans up previous PR: https://github.com/hpcc-systems/hpcc-jdbc/pull/136

JDBC-11 Add JDBC 4.1 (Java 1.7) support

---

pom.xml

JDBC-15 Remove SNAPSHOT from wsclient dep

---

pom.xml

INTERNAL Update JDBC package version

---

docs/JDBCDriver/hpcc_jdbc_driver.xml

Signed-off-by: Jim DeFabia <James.Defabia@LexisNexis.com>
@rpastrana Please review and merge

JDBC-16 Fix case on configuration attributes

---

docs/JDBCDriver/hpcc_jdbc_driver.xml

Signed-off-by: Jim DeFabia <James.Defabia@LexisNexis.com>
@rpastrana Please review and merge

JDBC-24 Update config attrs in docs

---

docs/JDBCDriver/hpcc_jdbc_driver.xml

Signed-off-by: Jim DeFabia <James.Defabia@LexisNexis.com>
@rpastrana Please review and merge

JDBC-12 Fix typos in Introduction

---

src/main/java/org/hpccsystems/jdbcdriver/HPCCResultSet.java
src/test/java/org/hpccsystems/jdbcdriver/tests/HPCCDriverTest.java

JDBC-29 TestSuite fix, and getRowcount warning

---

src/main/java/org/hpccsystems/jdbcdriver/HPCCJDBCUtils.java
src/main/java/org/hpccsystems/jdbcdriver/HPCCResultSet.java

JDBC-32 Map XSD types to SQL(JDBC) types

---

docs/BuildTools/xsltproc.cmake.in

JDBC-35 fix .in file

---

docs/common/Version.xml.in

JDBC-36 Update version to 2015

---

src/test/java/org/hpccsystems/jdbcdriver/tests/OrderedProperties.java

JDBC-37 Formating changes from code review

---

src/main/java/org/hpccsystems/jdbcdriver/DFUFile.java
src/main/java/org/hpccsystems/jdbcdriver/HPCCDatabaseMetaData.java

JDBC-38 Use WsClient File format enum

---

pom.xml
src/test/java/org/hpccsystems/jdbcdriver/tests/HPCCDriverTest.java

JDBC-39 Improve test suite

---

pom.xml

JDBC-41 Update pom to fetch dependancies

---

pom.xml

JDBC-45 Add MVN profile for test suite build

---

pom.xml

JDBC-45 Ensure MANIFEST contains main class

---

src/main/java/org/hpccsystems/jdbcdriver/HPCCPreparedStatement.java

Signed-off-by: Pastrana, Rodrigo <rodrigo.pastrana@lexisnexis.com>

JDBC-49 Properly serialize primitive types to string representation

---

src/main/java/org/hpccsystems/jdbcdriver/HPCCJDBCUtils.java
src/test/java/org/hpccsystems/jdbcdriver/tests/HPCCDriverTest.java

Signed-off-by: Pastrana, Rodrigo <rodrigo.pastrana@lexisnexis.com>

JDBC-53 Improve test suite reporting of converted vals

---

docs/JDBCDriver/hpcc_jdbc_driver.xml

Signed-off-by: Jim DeFabia James.Defabia@LexisNexis.com
@rpastrana Please review and merge

JDBC-52 Update Docs to clarify class path and class name explanation

---

pom.xml

Signed-off-by: Michael Gardner <michael.gardner@lexisnexis.com>

Central Migration - url added to pom.xml

---

CMakeLists.txt
version.cmake

@rpastrana one line was needed
Signed-off-by: Michael Gardner <michael.gardner@lexisnexis.com>

JDBC  Re-added include(version.cmake) for doc build

---

docs/common/Version.xml.in

Signed-off-by: Pastrana, Rodrigo <rodrigo.pastrana@lexisnexis.com>

JDBC-55 Update doc date 2015 -> 2017

---

pom.xml
src/main/java/org/hpccsystems/jdbcdriver/DFUFile.java
src/main/java/org/hpccsystems/jdbcdriver/HPCCConnection.java
src/main/java/org/hpccsystems/jdbcdriver/HPCCDatabaseMetaData.java
src/main/java/org/hpccsystems/jdbcdriver/HPCCDriver.java
src/main/java/org/hpccsystems/jdbcdriver/HPCCPreparedStatement.java
src/main/java/org/hpccsystems/jdbcdriver/HPCCResultSet.java
src/main/java/org/hpccsystems/jdbcdriver/HPCCStatement.java
src/main/resources/META-INF/services/java.sql.Driver

- Updated WSClient dependency to latest version
- Added meta-inf for autoloading SQL driver
- Fixed a bug related to reconnecting to a previous connection
- Fixed a bug related to caching meta data info
Signed-off-by: James McMullan James.McMullan@lexisnexis.com

JDBC-58 Update WSClient Dependency

---

pom.xml

Signed-off-by: Michael Gardner <michael.gardner@lexisnexisrisk.com>

JDBC pom version update for 1.0.2 release

---

pom.xml

Signed-off-by: Michael Gardner <michael.gardner@lexisnexisrisk.com>

JDBC pom version update for 1.0.4 release

---

pom.xml

Signed-off-by: Michael Gardner <michael.gardner@lexisnexisrisk.com>

pom gpg update

---

pom.xml

Signed-off-by: Michael Gardner <michael.gardner@lexisnexisrisk.com>

Developer information added to pom

---

bitools/tableau/README.md
bitools/tableau/example.properties
bitools/tableau/hpcc-jdbc.tdc

Signed-off-by: James McMullan James.McMullan@lexisnexis.com

JDBC-59 Publish BI Tool dialects for JDBC connectivity

---

pom.xml
src/main/java/org/hpccsystems/jdbcdriver/HPCCConnection.java

Signed-off-by: Rodrigo Pastrana <rodrigo.pastrana@lexisnexisrisk.com>

JDBC-61 Upgrade wsclient dep to latest

---

pom.xml
src/main/java/org/hpccsystems/jdbcdriver/DFUFile.java
src/main/java/org/hpccsystems/jdbcdriver/HPCCConnection.java
src/main/java/org/hpccsystems/jdbcdriver/HPCCDatabaseMetaData.java
src/main/java/org/hpccsystems/jdbcdriver/HPCCDriver.java
src/main/java/org/hpccsystems/jdbcdriver/HPCCLogicalFiles.java
src/main/java/org/hpccsystems/jdbcdriver/HPCCResultSet.java
src/test/java/org/hpccsystems/jdbcdriver/tests/HPCCDriverTest.java

- Update driver version
- Update dependency wsclient version to 9.12.x
- Clarify ServerAddress vs WsECLWatchAddress meaning
- Remove various HPCCConnection members
- Update log messages
- Avoid references to wsClient in favor of direct calls to wsdfuclient
- Avoid long WsSQL call for databases, targets wsdfu call instead
- Avoid fetchin full file metadata on all-table searches
- Ensure proper casing is used when fetching WsSQLPort connection properties
- Avoids null references
- Removes unnecessary log statements

HPCC4J-711 Modernize HPCCJDBC

---

README.md

HPCC4J-718 Update 1.2.0 README

---

pom.xml

- Fixed indentation
- Externalized multiple values
- Removed invalid configuration entry

HPCC4J-712 Fix pom issues from original commit
